title: JS Library documentation
description: A JavaScript library for building performant and quick search experiences with Unbxd.
theme: just-the-docs

url: https://akshayunbxd.github.io

logo: "https://unbxd.com/static/new-unbxd-logo-7f8465b0fbaa773dcac9bc14897f7d34.svg"

aux_links:
  Template Repository: https://github.com/akshayunbxd/search-JS-library/

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; © 2022 <a href=\"https://unbxd.com/\">Unbxd</a> Inc, All Rights Reserved."

