name: searchJsLibrary
on:
    pull_request:
    push:
env:
    CODECOV_TOKEN: '${{ secrets.CODECOV_TOKEN }}'
    GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    NPM_TOKEN: '${{ secrets.NPM_TOKEN }}'
defaults:
    run:
        shell: bash
jobs:

    publish-to-master:
        name: Publish to master
        # needs: publish
        # if: github.event_name == 'push' && github.ref == 'refs/heads/feature-workflows'
        runs-on: ubuntu-latest
        steps:
            - name: Pre-reqs
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: 15

            - name: Check Cache
              uses: actions/cache@v2
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

            - name: Install Dependencies
              run: yarn install --frozen-lockfile

            - name: Run Build
              run: yarn build:prod

            - name: Configure AWS credentials
              id: configure-aws
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1

            - name: Extract version
              id: extract_version
              uses: Saionaro/extract-package-version@v1.0.6

            - name: Print version
              run: echo ${{ steps.extract_version.outputs.version }}

            - name: Run aws cp command
              id: aws-upload
              env:
                AWS_DISTRIBUTION_ID: ${{ secrets.AWS_DISTRIBUTION_ID }}
                DEPLOY_ENV: ${{ steps.infer_env.outputs.DEPLOY_ENV }}
              run: |
                aws s3 cp public/dist/js/vanillaSearch.min.js s3://unbxd/search-sdk/vvv${{ steps.extract_version.outputs.version }}/vanillaSearch.min.js --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers --cache-control 'public,max-age=2592000' --content-encoding 'gzip'