name: searchJsLibrary
on:
    pull_request:
    push:
env:
    CODECOV_TOKEN: '${{ secrets.CODECOV_TOKEN }}'
    GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    NPM_TOKEN: '${{ secrets.NPM_TOKEN }}'
defaults:
    run:
        shell: bash
jobs:
    
    publish-to-prod:
    
        name: Publish To Prod 🚀
        runs-on: ubuntu-latest
        steps:
            - name: Akshay
              uses: actions/checkout@v2
